# Numpy

Nama: Windy Mega Melani
<br>
Code: PYTN-KS04-003
<br>
Python for Data Science

In [1]:
import numpy as np

In [2]:
arrayA=np.array([0,2,4,6,8,10])
arrayA

array([ 0,  2,  4,  6,  8, 10])

In [3]:
listA=[1,2,3,4,5]
mullist=listA*2
mularray=arrayA*2

print(mullist)
print(mularray)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 0  4  8 12 16 20]


In [4]:
np.append(arrayA, [6,12])

array([ 0,  2,  4,  6,  8, 10,  6, 12])

In [5]:
np.delete(arrayA, 5)

array([0, 2, 4, 6, 8])

In [6]:
arrayA.shape

(6,)

In [7]:
arrayB = np.expand_dims(arrayA, axis=1)
arrayB.shape

(6, 1)

In [8]:
data=np.array([1,2,3])

print(data)
print(data[0])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
[1 2]
[2 3]
[2 3]


In [9]:
print(arrayA[arrayA>=5])

[ 6  8 10]


In [10]:
five_up = (arrayA >=5)
print(arrayA[five_up])
print(arrayA[arrayA>=5])

[ 6  8 10]
[ 6  8 10]


In [11]:
dibagi_dua = arrayA[arrayA%2==0]
print(dibagi_dua)

[ 0  2  4  6  8 10]


In [12]:
arrayC = arrayA[(arrayA>2) & (arrayA<11)]
print(arrayC)

[ 4  6  8 10]


In [13]:
contoharray = np.array([[1,2,3,4,5,6,7,8,9,10],
                       [11,12,13,14,15,16,17,18,19,20]])
                        
print(contoharray)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [14]:
arrsplit=np.array([[1,2,3,4,5,6,7,8,9,10],
                  [11,12,13,14,15,16,17,18,19,20]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [15]:
np.hsplit(arrsplit,2)

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]),
 array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]])]

In [16]:
arrayB=arrayA.view()
arrayB

array([ 0,  2,  4,  6,  8, 10])

In [17]:
arrayC=arrayA.copy()
arrayC

array([ 0,  2,  4,  6,  8, 10])

In [18]:
arrayA.sum()

30

In [19]:
arrayB=np.array([[1,1],[2,2]])
arrayB.sum(axis=0)

array([3, 3])

In [20]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [21]:
data+ones

array([2., 3., 4.])

In [22]:
data*data

array([1, 4, 9])

In [23]:
data/data

array([1., 1., 1.])

In [24]:
data*2

array([2, 4, 6])

In [25]:
data.min()

1

In [26]:
data.std()

0.816496580927726

In [27]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
print(a1.shape)

a2=np.array([[7,8],[9,10],[11,12]])
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [28]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [29]:
print(a1.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
print(np.random.random((4,3,2)))

[[[0.33779891 0.70640419]
  [0.58955765 0.47723813]
  [0.74839835 0.50964871]]

 [[0.56214858 0.62495832]
  [0.38420484 0.49406321]
  [0.72366548 0.23041888]]

 [[0.8585747  0.33430326]
  [0.590602   0.91251342]
  [0.78713924 0.72049664]]

 [[0.26385671 0.6422374 ]
  [0.59224096 0.94293567]
  [0.56558015 0.13897518]]]


In [31]:
a1.flatten()

array([1, 2, 3, 4, 5, 6])